// ----------------------------------------------------------------------------------------------------
// PROJECT INFORMATION

// NAME:  R/C Mower Trailer
// REVISION:  A1
// START DATE:  8/20/2021
// CURRENT VERSION DATE:  9/8/2021
// LICENSE:  GPLv3
// AUTHOR:  Justin Grimes (@zelon88)
// DESCRIPTION:  A tow-behind lawn mowing attachment for retrofit onto low-speed R/C vehicles.
// ----------------------------------------------------------------------------------------------------

// ----------------------------------------------------------------------------------------------------
// PART INFORMATION

// NAME:  Differential Gears
// REVISION:  A1
// START DATE:  7/16/2026
// CURRENT VERSION DATE:  7/16/2026
// AUTHOR:  Justin Grimes (@zelon88)
// DESCRIPTION:
//    The planetary bevel gear set for the center differential.
//    Consists of a central core block, two Output Gears (one per motor), and four Planet Gears
//    arranged around the core in the X-Z plane. The core block and gear bores are sized for
//    F3-6-2.8M thrust bearings and 5x8mm flanged bearings on the Output Shafts.
//    Gear tooth profiles are generated by the public domain involute gear library in Workfiles/Gears.scad.
// FILE NAME: Differential_Gears.scad
// ----------------------------------------------------------------------------------------------------

// ----------------------------------------------------------------------------------------------------
// PRINTER CONFIGURATION
// [Printing instructions to be added]
// ----------------------------------------------------------------------------------------------------

// ----------------------------------------------------------------------------------------------------
// MANUFACTURING INSTRUCTIONS

// 1. Slide an M2.5 Wave Compression Washer and a Flanged 5x8mm Bearing onto the Output Shaft of an Output Gear.
//   1-A. The flange of the bearing should be facing the gear.
// 2. Install one Output Gear into the Differential Housing.
// 3. Slide the Output Gear through bolt through the housing and output gear, but do not install the nut.
// 4. Slide the Core Block over the Output Gear through bolt.
//   4-A. Take care to install the Core Block in the proper orientation.
// 5. Install the Planet Gears into the housing with two F3-6-2.8M Thrust Bearings per gear, one per side.
//   5-A. Each Planet Gear should have 2 bearings each.
// 6. Install one M2.5 Conical Compression Washer on the outside face of the outer F3-6-2.8M thrust bearing on each Planet Gear.
//   6-A. The small diameter of the Conical Compression Washer should face towards the Planet Gear.
//   6-B. The large diameter of the Conical Compression Washer should face towards the bearing.
// 7. Test fit each of the 4 Planet Gear Screws through each Planet Gear.
//   7-A. Install an equal number of flat washers on each side of each planet screw until there is no more slack in the gears.
//   7-B. Each Planet Gear screw should pass through the Differential Housing, a Conical Compression Washer, a F3-6-2.8M
//        Thrust Bearing, a Planet Gear, another F3-6-2.8M Thrust Bearing, an equal amount of flat washers on either
//        side of the thrust bearings, and finally thread snugly into the Core Block.
//   7-C. Apply a small amount of liquid thread locker onto the Planet Gear screws prior to final assembly.
// 8. Slide an M2.5 Wave Compression Washer and a Flanged 5x8mm Bearing onto the Output Shaft of the remaining Output Gear.
//   8-A. The flange of the bearing should be facing the gear.
// 9. Slide the second Output Gear onto the Output Gear bolt.
// 10. Install the Differential Gear Cover.
//   10-A. The cover rotates to lock into place.
//   10-B. The cover is fully seated and locked into place when all Differential Housing screw holes line up.
// 11. Install the Differential Housing into the Center Bracket.
// 12. Install the Differential Housing mounting screws.
// ----------------------------------------------------------------------------------------------------

// ----------------------------------------------------------------------------------------------------
// MODULES

// The public domain parametric involute gear library used to generate the gear tooth profiles.
include <Workfiles/Gears.scad>;
// A module for creating low-poly representations of the bearings used in the assembly.
include <Workfiles/Bearings.scad>;
// ----------------------------------------------------------------------------------------------------

// ----------------------------------------------------------------------------------------------------
// GEOMETRY

// Geometry constraints reflecting the clearance available inside the Differential Housing.
// The maximum hypothetical diameter that all moving parts must stay within. Applies strictly to the internal gears.
max_diameter = 21.75;
// The maximum width that all moving parts must stay within. Applies strictly to the internal gears.
max_width = 14.50;

// Basic constraints adjustable from the dimensional requirements of the assembly.
// Changes to these variables will require significant adjustment to integrate.
// The diameter of the Output Shafts, measured in mm.
output_shaft_dia = 5.0;
// The diameter of the Planet Shafts, measured in mm.
planet_shaft_dia = 6.0;
// Extension distance beyond the housing constraints for bearings and casings, measured in mm.
shaft_extension = 5.0;
// Offset the 5x8 bearings outward or inward along the Output Shafts, measured in mm.
bearing_offset = 5.75;
// Adjust mesh clearance.
mesh_clearance = 0.45;

// Calculated parameters derived from the dimensional requirements of the assembly.
// Changes to these variables will require significant geometric adjustments to integrate.
// The number of teeth on each Output Gear.
side_teeth = 16;
// The number of teeth on each Planet Gear.
planet_teeth = 12;
// The space between each tooth, measured in mm.
mm_per_tooth = 3.0;
// The total number of Planet Gears.
num_planets = 4;
// The side length of the square slot cut into the Output Shafts for driveshaft rotational engagement, measured in mm.
flat_width = 2.50;
// Expanded addendum calculation to let the tooth shapes grow longer.
addendum = (mm_per_tooth / 3.14159265) * 1.5;
// The diameter of the Output Gears, measured in mm. (~15.28mm)
side_pd = (side_teeth * mm_per_tooth) / 3.14159265;
// The diameter of the Planet Gears, measured in mm. (~11.46mm)
planet_pd = (planet_teeth * mm_per_tooth) / 3.14159265;
// The face width of the gear teeth, measured in mm.
gear_h = 3.0;
// Calculate the scaling factor for tapering the teeth toward the apex.
side_outer_r = side_pd / 2;
side_inner_r = side_outer_r - gear_h;
side_scale = side_inner_r / side_outer_r;
planet_outer_r = planet_pd / 2;
planet_inner_r = planet_outer_r - gear_h;
planet_scale = planet_inner_r / planet_outer_r;
// The distance from the origin, including clearance padding.
side_distance = (planet_pd / 2) + mesh_clearance;
planet_distance = (side_pd / 2) + mesh_clearance;
// Dynamic calculation ensuring the shaft fills the main housing boundary and adds the extension specified above.
total_shaft_len = ((max_width / 2) - side_distance) + shaft_extension;
// Cap the square slot size at 99% of the Output Shaft diameter to prevent it from exceeding the shaft.
safe_flat_width = min(flat_width, output_shaft_dia * 0.99);
// Set the rendering resolution for the entire assembly.
$fn = 128;

module cross_block_core() {
  color("DarkGray") {
    difference() {
      // Create the main solid bounding cube derived from exact face metrics.
      cube([6.58, 6.36, 6.58], center=true);

      // Cut the through-hole along the Y axis.
      rotate([0, 90, 0]) cylinder(h=10, r=1.43, center=true);
      // Cut the through-hole along the X axis.
      rotate([90, 0, 0]) cylinder(h=10, r=1.43, center=true);
      // Cut the through-hole along the Z axis. Concentric hole for the vertical planet pair.
      translate([0, 0, 0]) cylinder(h=10, r=1.43, center=true);

      // Cut the counterbore reliefs along the Y axis.
      translate([4, 0, 0]) rotate([0, 90, 0]) cylinder(h=2, r=3.02, center=true);
      translate([-4, 0, 0]) rotate([0, 90, 0]) cylinder(h=2, r=3.02, center=true);
      // Cut the counterbore reliefs along the X axis.
      translate([0, 4, 0]) rotate([90, 0, 0]) cylinder(h=2, r=3.02, center=true);
      translate([0, -4, 0]) rotate([90, 0, 0]) cylinder(h=2, r=3.02, center=true);
      // Cut the counterbore reliefs along the Z axis. Concentric holes for the vertical planet pair.
      translate([0, 0, 4]) cylinder(h=2, r=3.02, center=true);
      translate([0, 0, -4]) cylinder(h=2, r=3.02, center=true); } } }

// Base bevel generator. Large diameter at Z=0, tapering to small diameter at Z=gear_h.
module side_gear_with_shaft() {
  difference() {
    union() {
      difference() {
        union() {
          // Create the main tapered cone body.
          cylinder(h=gear_h, r1=side_outer_r - 0.6, r2=side_inner_r - 0.6, center=false);
          // Create the output shaft, projecting through the core with an extension beyond it.
          translate([0, 0, -total_shaft_len]) cylinder(h=total_shaft_len, r=output_shaft_dia/2, center=false);
          // Shoulder between gear rear face (Z=0) and flanged bearing near face.
          // bearing_offset positions the FAR face of the bearing at Z=-bearing_offset.
          // Near (flange) face is at Z=-(bearing_offset - 2.5) — 2.5mm = bearing width.
          // 1.375mm washer stack budget: flat washer + wave washer + flat washer, tight pre-load.
          // Shoulder length = bearing_offset - 2.5 - 1.375 = bearing_offset - 3.875.
          // Sand shoulder face to dial in pre-load — design intentionally runs slightly tight.
          // r exceeds bearing bore r=2.5mm so the shoulder cannot pass through the bearing,
          // preventing lateral sliding & loss of planet engagement.
          translate([0, 0, -(bearing_offset - 3.875)]) cylinder(h=bearing_offset - 3.875, r=output_shaft_dia/2 + 1.5, center=false); }

        // Cut a hexagonal slot through the shaft for driveshaft rotational engagement.
        // $fn=6 gives 6 engagement faces and seats in any of 6 orientations (60deg apart)
        // making assembly easy while still providing strong rotational engagement.
        // Vertices at r=2.0mm from center (shaft r=2.5mm — 0.5mm wall at each tip).
        // Flat faces (apothem) at r*cos(30deg)=1.732mm — outside bore r=1.5mm.
        // Increase r toward 2.2mm for more engagement; decrease toward 1.6mm for more wall.
        translate([0, 0, -total_shaft_len / 2])
          cylinder($fn=6, r=2.0, h=total_shaft_len + 2, center=true); }

      // Create the tapered bevel teeth.
      intersection() {
        cylinder(h=gear_h, r1=side_outer_r + addendum, r2=side_inner_r + (addendum * side_scale), center=false);
        linear_extrude(height=gear_h, twist=0, scale=side_scale)
          projection(cut=true)
            translate([0, 0, -0.5]) gear(number_of_teeth=side_teeth, mm_per_tooth=mm_per_tooth, thickness=2, center=true); } }

    // Cut the final master cylindrical bore.
    translate([0, 0, -(total_shaft_len + gear_h)]) cylinder(h=(total_shaft_len + gear_h) * 2, r=1.22);

    // Cut a shallow recess into the narrow inside face (Z=gear_h plane) for the Y axis thrust bearing.
    // Kept shallow (0.8mm deep) to preserve strength in the gear hub.
    translate([0, 0, gear_h - 0.8]) cylinder(h=1.0, r=6.1/2, center=false); } }

module planet_bevel_gear() {
  difference() {
    union() {
      difference() {
        cylinder(h=gear_h, r1=planet_outer_r - 0.6, r2=planet_inner_r - 0.6, center=false);
        translate([0, 0, -1]) cylinder(h=gear_h + 2, r=planet_shaft_dia/2); }
      intersection() {
        cylinder(h=gear_h, r1=planet_outer_r + addendum, r2=planet_inner_r + (addendum * planet_scale), center=false);
        linear_extrude(height=gear_h, twist=0, scale=planet_scale)
          projection(cut=true)
            translate([0, 0, -0.5]) gear(number_of_teeth=planet_teeth, mm_per_tooth=mm_per_tooth, thickness=2, center=true); } }
    translate([0, 0, -2]) cylinder(h=gear_h + 4, r=1.22);
    translate([0, 0, -0.1]) cylinder(h=1.1, r=6.1/2);
    translate([0, 0, gear_h - 1.0]) cylinder(h=1.1, r=6.1/2); } }

module Differential_Assembly() {
  // Create the core manifold block that locks the center vacancy.
  cross_block_core();

  // Create the right side gear, positioned along +Y, pointing toward center.
  translate([0, side_distance, 0]) rotate([90, 0, 0]) side_gear_with_shaft();
  // Create the right output bearing, adjusted along +Y.
  translate([0, side_distance + bearing_offset, 0]) rotate([90, 0, 0]) flanged_bearing_5x8x2_5();
  // Create the right inner thrust bearing, seated 2mm inside the block face along Y.
  translate([0, 2, 0]) rotate([0, 90, 90]) f3_6_2_8m_bearing();

  // Create the left side gear, positioned along -Y, pointing toward center.
  translate([0, -side_distance, 0]) rotate([-90, 0, 0]) side_gear_with_shaft();
  // Create the left output bearing, adjusted along -Y.
  translate([0, -(side_distance + bearing_offset), 0]) rotate([-90, 0, 0]) flanged_bearing_5x8x2_5();
  // Create the left inner thrust bearing, seated 2mm inside the block face along Y.
  translate([0, -2, 0]) rotate([0, 90, -90]) f3_6_2_8m_bearing();

  // Create the 4 cross-planet bevel gears and bearing stacks, arranged in the X-Z plane.
  for (i = [0:num_planets - 1]) {
    angle = i * (360 / num_planets);
    rotate([0, angle, 0]) {
      translate([0, 0, planet_distance]) rotate([180, 0, 0]) planet_bevel_gear();
      translate([0, 0, planet_distance - gear_h - 2.8 + 1.0]) f3_6_2_8m_bearing();
      translate([0, 0, planet_distance - 1.0]) f3_6_2_8m_bearing(); } } }

// Render the object.
// Comment or uncomment as needed.
//Differential_Assembly();

// Render the object for printing.
// Comment or uncomment as needed.
// The Bevel Gears.
//translate([19.5, 4, 0]) rotate([0, 0, 12.5]) planet_bevel_gear();
//translate([-19.5, 4, 0]) rotate([0, 0, -12.5]) planet_bevel_gear();
//translate([7.5, 7.5, 0]) planet_bevel_gear();
//translate([-7.5, 7.5, 0]) planet_bevel_gear();
// The Output Gears.
//translate([10, -7.5, gear_h]) rotate([0, 180, 0]) side_gear_with_shaft();
//translate([-10, -7.5, gear_h]) rotate([0, 180, 0]) side_gear_with_shaft();
// The Core Block.
//translate([0, 0, 6.58 / 2]) rotate([0, 0, 45]) cross_block_core();
// ----------------------------------------------------------------------------------------------------